# Generated by Django 5.0.2 on 2024-03-10 16:52

import django.db.models.deletion
import lobbies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lobby",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lobbies.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "url_code",
                    models.CharField(
                        default=lobbies.utils.generate_short_url,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("max_players", models.IntegerField()),
                (
                    "security_token",
                    models.CharField(
                        default=lobbies.utils.generate_security_token,
                        editable=False,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("game_started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lobbies.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=1000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lobbies.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lobby",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lobbies.lobby",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lobby",
            name="questions",
            field=models.ManyToManyField(blank=True, to="lobbies.question"),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lobbies.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=1000)),
                (
                    "lobby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lobbies.lobby"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lobbies.player"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lobbies.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
